### ISSUE TITLE
CentOS 7: QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by keith4743** [shadowsocks/shadowsocks-qt5#424]
运行ss-qt5的时候报错

QXcbConnection: Could not connect to display 
Aborted

而且，我没有~/.config/shadowsocks-qt5/ 这个目录。

这个要怎么配置，我用的系统是centos7.2。

**Comment by keith4743** [comment]
resolved.

**Comment by IEEE756** [comment]
have the same problem , how to solve it, thanks ?

**Comment by IEEE756** [comment]
@KeithTt have the same problem , how to solve it, thanks ?

**Comment by vic-feng** [comment]
Please try again:
mkdir -p ~/.config/shadowsocks-qt5/

**Comment by IEEE756** [comment]
@vic-feng still have the problem
`[root@videosys yum.repos.d]# mkdir -p ~/.config/shadowsocks-qt5/
[root@videosys yum.repos.d]# ss-qt5
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
`
